### ISSUE TITLE
Request for location hint

### ISSUE THREAD

**Issue by dth9269** [ginkgobioworks/vaccinetime#2]
Hi there.  Been following the twitter account for a while now, and would like to request a minor enhancement.  Certain vaccination locations (e.g. McCloskey School Gymnasium) have no associated detail re. municipality (unlike, e.g. Greenfield Senior Center).  In such cases it would be handy to have a town/city name added, perhaps as a Twitter tag like #BostonMA.  Note that UMass Memorial is also ambiguous in this way.

Keep up the good work!

**Comment by dpca** [comment]
I modified the MaImmunizations and MyChart scrapers to include the town name in tweets going forward, I think the other sites mostly have that information already. An example tweet with the new text would be:

```
10 appointments available at McCloskey School Gymnasium in Uxbridge MA on 03/25/2021. Check eligibility and sign up at https://www.maimmunizations.org/clinic/search?q[venue_search_name_or_venue_name_i_cont]=McCloskey%20School%20Gymnasium&
```

(the "in Uxbridge MA" is the new part)

Thanks for the suggestion!
