### ISSUE TITLE
MA Walgreens appointment?

### ISSUE THREAD

**Issue by LrngToFly** [ginkgobioworks/vaccinetime#3]
I am not seeing Walgreens appointments being posted, although I only scrolled back through about five days of tweets.  If they’re not already being posted , can you scrape for their data as well?  Thank you!

**Comment by peterlazzarino** [comment]
@LrngToFly @dpca Walgreens currently returns the following when vaccines are available

```
appointmentsAvailable: true
availabilityGroups: ["General"]
days: 5
radius: 25
stateCode: "MA"
stateName: "Massachusetts"
zipCode: "02155"
````

The next step is a full set of screening questions, would it be sufficient to scrape for this without an appointment count? I did some work on getting a scraper set up for RI clinics and could put an MR together for this if its useful.

**Comment by dpca** [comment]
The CVS scraper grabs the town names where appointments are and counts each town as one appointment. Maybe Walgreens could work the same way? I think it would be nice to at least verify that a few stores have appointments, so we don't tweet for one off cancellations.

**Comment by sgarfinkel** [comment]
This project has several scrapers that could be adapted for this project, including Walgreens:
https://github.com/GUI/covid-vaccine-spotter/tree/main/src/providers

@dpca Are you currently working on this ticket? I know very little Ruby but might try to muddle through on this ticket.

**Comment by dpca** [comment]
Nice find with vaccinespotter @sgarfinkel! I did a little bit of digging around the Walgreens API myself but they're quick to start requiring captchas and rate limiting by IP, so I didn't get very far. I'll take a look at the vaccinespotter API and try to use that, if that's easy to use I should be able to get something working by today. Thanks for the tip!

**Comment by sgarfinkel** [comment]
@dpca The per-store endpoint is deprecated FYI

**Comment by dpca** [comment]
I used the `https://www.vaccinespotter.org/api/v0/states/MA.json` API and let it scrape all the pharmacies besides CVS. Hopefully that means we get Shaws and Star Market for free!

**Comment by LrngToFly** [comment]
Very nice!  Thank you!  Have used your twitter bot to help get three appointments.  Much appreciated.

**Comment by LrngToFly** [comment]
I see the first of the MA Walgreens tweets.  Awesome- thanks again for all the work!
